# Generated by Django 4.1.13 on 2024-02-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='img',
        ),
    ]
